# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{acts_as_licensable}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alex Roberts"]
  s.date = %q{2010-11-02}
  s.description = %q{License your Active Record objects with various free/open source licenses}
  s.email = %q{alex@redprocess.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "README",
     "Rakefile",
     "VERSION",
     "fixtures/licenses.yml",
     "install.rb",
     "lib/acts_as_licensable.rb",
     "lib/acts_as_licensable/acts_as_licensable.rb",
     "lib/acts_as_licensable/acts_as_licensable_helper.rb",
     "lib/acts_as_licensable/license.rb",
     "lib/acts_as_licensable/licensing.rb",
     "lib/generators/acts_as_licensable/migration/USAGE",
     "lib/generators/acts_as_licensable/migration/migration_generator.rb",
     "lib/generators/acts_as_licensable/migration/templates/active_record/migration.rb",
     "lib/tasks/acts_as_licensable_tasks.rake",
     "rails/init.rb",
     "test/acts_as_licensable_test.rb",
     "test/database.yml",
     "test/fixtures/book.rb",
     "test/schema.rb",
     "test/test_helper.rb",
     "uninstall.rb"
  ]
  s.homepage = %q{https://github.com/mralex/acts_as_licensable}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{License your Active Record objects with various free/open source licenses}
  s.test_files = [
    "test/acts_as_licensable_test.rb",
     "test/fixtures/book.rb",
     "test/schema.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

